### ISSUE TITLE
Wrong manifest main class rx3grpc

### ISSUE THREAD

**Issue by rys-gw-wal** [salesforce/reactive-grpc#260]
I've tried to use rx3grpc with gradle and I've found a problem.

description:
file: reactive-grpc/rx3-java/rx3grpc/pom.xml

Manifest main class  should be changed:
com.salesforce.rx3grpc.RxGrpcGenerator -> com.salesforce.rx3grpc.Rx3GrpcGenerator

**Comment by rmichela** [comment]
Is this affecting Gradle?

**Comment by scottslewis** [comment]
I believe this problem will/does affect any attempt to use any of the generator binaries for rx3grpc...e.g.  rx3grpc-windows-x86_64-1.2.2.exe since the reactive-grpc produces these binaries during build as per @rys-gw-wal original observation.    I'm producing a pr with the fix (RxGrpcGenerator -> Rx3GrpcGenerator) 

Created pr #261 to apply fix.  I see that the top-level version number has been updated (from 1.2.2 deployed to 1.2.3 now).  If at all possible I would appreciate the release of 1.2.3 as soon as is possible so that this fix can be consumed by myself and @rys-gw-wal at least.

**Comment by rmichela** [comment]
See #262
