### ISSUE TITLE
Java ➜ GoLang Interop Testing

### ISSUE THREAD

**Issue by rmichela** [salesforce/reactive-grpc#92]
Write a gRPC server in GoLang and use Reactive gRPC to call it. Make sure the following work correctly.

* One-to-one
* One-to-many
* Many-to-one
* Many-to-many

**Comment by rickeyski** [comment]
Hey,

Do you have a specific service(proto) file that you would like implemented for this and #93? Otherwise, I can throw one together.

How would you like this integrated into the projects file structure? My thought is adding a top level integration folder, then have go, csharp, proto, and java subfolders with the respective servers and client. 
```
/common
/demos
/integration
  /go-server
  /csharp-server
  /java-client
  /proto
```

They would all be managed by a bazel, based off of this [article](https://grpc.io/blog/bazel_rules_protobuf). I am open to a better way of doing a multi-language build or if this is just over-complicating, but I believe it's the simplest way to do a multi-language build for this.

Thanks,
Rickey

**Comment by cbornet** [comment]
I guess the original [gRPC interop test suite](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md) could be used

**Comment by rmichela** [comment]
Maven's `maven-compiler-plugin` in theory supports [executing other compilers](http://maven.apache.org/plugins/maven-compiler-plugin/non-javac-compilers.html), but I have no idea how well implemented this is.

[`mvn-golang`](https://github.com/raydac/mvn-golang) and [`dotnet-maven-plugin`](https://github.com/kaspersorensen/dotnet-maven-plugin) also look promising.

gRPC Java uses bazel and gradle in the same repo. I'd be open to bazel and maven in the same repo if cross-language compilation with Maven proves unreliable.

**Comment by rickeyski** [comment]
I try out the maven plugins. Not sure it's worth introducing an entirely new build system for integration tests.

**Comment by rmichela** [comment]
Thank you so much for taking integration testing on!

**Comment by rmichela** [comment]
If you need to, you can put the maven parts in a profile that is disabled by default. That way interop tests won't run during CI builds. Getting a .NET Core and Golang environment working in CI could prove challenging and doesn't need to hold up the initial work.

**Comment by rmichela** [comment]
I reused the gRPC interop demo I did for a conference talk. Added stream testing and unary testing.
